In [ ]:
import pandas as pd

After importing pandas, we are going to utilize this CSV file to get all the data related to baby names within the US

https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv

In [ ]:
baby_names = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv")

Convert the CSV file that we grab online and feed into the following function

```
pd.read_csv("URL")
```
This will parse the CSV file into a Pandas DataFrame
Next we'll display the first 10 entries of the DataFrame

In [ ]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

Pandas core object called DataFrame allow us to access several methods that not only allow us to read the data, but also to create, manipulate and delete data within the DataFrame

In [ ]:
print(type(baby_names))

<class 'pandas.core.frame.DataFrame'>

Using the following function


```
DataFrame.sort_values("Coloum Name", ascending=0)
```
We are able to sort out DataFrame based on a certain coloumn, it can display names and numbers in ascending order

In [ ]:
baby_names.sort_values("Count", ascending=0).head(5)

        Unnamed: 0      Id     Name  Year Gender State  Count
107416      678593  678594   Daniel  2004      M    CA   4167
110097      681274  681275   Daniel  2005      M    CA   3914
115739      686916  686917   Daniel  2007      M    CA   3865
112872      684049  684050   Daniel  2006      M    CA   3826
107417      678594  678595  Anthony  2004      M    CA   3805

This following allows us to group the rows together (Since rows and baby names are split, look at David for example). We group the rows based on baby names and then sort by count.

This allows us to get the true most popular baby name, which is Jacob!

In [ ]:
popular_names = baby_names.groupby("Name").sum()
popular_names_asc = popular_names.sort_values("Count", ascending=0)
popular_names_asc["Count"].head(10)

<ipython-input-13-d74d7f890db7>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  popular_names = baby_names.groupby("Name").sum()

Name
Jacob       242874
Emma        214852
Michael     214405
Ethan       209277
Isabella    204798
William     197894
Joshua      191551
Sophia      191446
Daniel      191440
Emily       190318
Name: Count, dtype: int64