In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
df = pd.read_csv("./sample_data/california_housing_test.csv")

In [3]:
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

In [47]:
df_miss = pd.read_csv("./sample_data/california_housing_test_incomplete.csv")

In [48]:
df_miss.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27,3885.0,661,1537,606,6.6085,344700
1,-118.30,34.26,43,NaN,310,809,277,3.5990,0
2,-117.81,33.78,27,NaN,507,1484,495,5.7934,0
3,-118.36,33.82,28,NaN,15,49,11,6.1359,0
4,-119.67,36.33,19,NaN,244,850,237,2.9375,0
5,-119.56,36.51,37,NaN,213,663,204,1.6635,0
6,-121.43,38.63,43,NaN,225,604,218,1.6641,0
7,-120.65,35.48,19,NaN,471,1341,441,3.2250,0
8,-122.84,38.40,15,NaN,617,1446,599,3.6696,0
9,-118.02,34.08,31,NaN,632,2830,603,2.3333,0

In [49]:
print(df_miss.isnull())

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0         False     False               False        False           False
1         False     False               False         True           False
2         False     False               False         True           False
3         False     False               False         True           False
4         False     False               False         True           False
...         ...       ...                 ...          ...             ...
2995      False     False               False        False           False
2996      False     False               False        False           False
2997      False     False               False        False           False
2998      False     False               False        False           False
2999      False     False               False        False           False

      population  households  median_income  median_house_value
0          False       False          False               False
1          False       False          False               False
2          False       False          False               False
3          False       False          False               False
4          False       False          False               False
...          ...         ...            ...                 ...
2995       False       False          False               False
2996       False       False          False               False
2997       False       False          False               False
2998       False       False          False               False
2999       False       False          False               False

[3000 rows x 9 columns]

In [50]:
df_miss.sort_values("median_house_value", ascending=True).head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
260,-119.03,35.38,52,NaN,290,540,260,2.7312,0
223,-118.27,34.10,50,NaN,398,793,418,4.7132,0
222,-118.19,33.91,43,NaN,357,1509,376,2.6354,0
221,-121.49,38.51,30,NaN,607,1857,579,3.1768,0
220,-122.18,37.78,33,NaN,31,575,47,3.8750,0
219,-117.90,33.60,25,NaN,585,906,472,3.6538,0
218,-122.28,38.34,44,NaN,190,416,174,3.6389,0
217,-117.18,34.48,8,NaN,691,2156,659,2.7778,0
224,-121.44,38.61,34,NaN,38,149,55,2.6442,0
216,-121.64,37.14,14,NaN,1024,2823,979,4.1750,0

In [51]:
df_miss.fillna(0, inplace=True)
df_miss.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27,3885.0,661,1537,606,6.6085,344700
1,-118.30,34.26,43,0.0,310,809,277,3.5990,0
2,-117.81,33.78,27,0.0,507,1484,495,5.7934,0
3,-118.36,33.82,28,0.0,15,49,11,6.1359,0
4,-119.67,36.33,19,0.0,244,850,237,2.9375,0
5,-119.56,36.51,37,0.0,213,663,204,1.6635,0
6,-121.43,38.63,43,0.0,225,604,218,1.6641,0
7,-120.65,35.48,19,0.0,471,1341,441,3.2250,0
8,-122.84,38.40,15,0.0,617,1446,599,3.6696,0
9,-118.02,34.08,31,0.0,632,2830,603,2.3333,0

In [75]:
z = np.abs(stats.zscore(df_miss))
print(z)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0      1.233729  0.814633            0.147000     0.690086        0.315337
1      0.646344  0.645931            1.127565     1.109001        0.529255
2      0.892007  0.871356            0.147000     1.109001        0.055225
3      0.616263  0.852570            0.067340     1.109001        1.239098
4      0.040509  0.326213            0.784282     1.109001        0.688068
...         ...       ...                 ...          ...             ...
2995   0.135766  0.570789            0.465641     0.437527        0.269618
2996   0.726560  0.739858            0.147000     1.325439        1.328367
2997   0.055550  0.312124            1.501225     0.666291        0.791536
2998   1.237940  0.721072            0.888584     1.064545        1.241504
2999   0.020455  0.570789            1.047905     0.291655        0.642349

      population  households  median_income  median_house_value
0       0.130246    0.317734       1.510745            1.279845
1       0.576296    0.582743       0.112324            1.469326
2       0.078808    0.013926       1.071149            1.469326
3       1.313894    1.310788       1.255865            1.469326
4       0.536504    0.692223       0.469081            1.469326
...          ...         ...            ...                 ...
2995    0.140531    0.320471       1.417467            0.325172
2996    2.031502    1.494650       0.224718            0.422473
2997    0.688877    0.738753       0.818558            0.974842
2998    1.316806    1.302577       0.289327            0.173300
2999    0.630645    0.629272       2.563651            2.518455

[3000 rows x 9 columns]

In [77]:
threshold = 1.25
df_fixed = df_miss[(z < threshold).all(axis=1)]
df_fixed

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
304,-117.84,35.35,28,1913.0,486,858,371,1.9962,50800
309,-118.27,34.11,36,1832.0,539,934,486,3.0521,276600
310,-118.44,34.30,38,1595.0,314,1181,327,3.4000,155500
311,-121.77,37.68,41,1501.0,299,629,288,4.6806,209400
318,-118.07,33.91,29,2387.0,570,1978,548,3.1957,159200
...,...,...,...,...,...,...,...,...,...
2985,-120.47,34.94,17,1368.0,308,642,303,1.8633,109400
2987,-121.97,37.29,25,4096.0,743,2027,741,5.3294,300300
2988,-122.01,36.97,43,2162.0,509,1208,464,2.5417,260900
2989,-122.02,37.60,32,1295.0,295,1097,328,3.2386,149600
2994,-117.93,33.86,35,931.0,181,516,174,5.5867,182500